planning_horizon: 12
num_candidates: 256
gamma: 0.99
action_sample_std: 0.4

hidden_sizes: [128, 128]
lr: 3e-4
train_freq: 50
gradient_steps: 5
batch_size: 256
buffer_size: 100000
warmup_steps: 2000
weight_decay: 1e-5
predict_delta: true

eval_freq: 2000
eval_episodes: 5
model_save_path: ./runs/dynamics_model.pt
